### ISSUE TITLE
fabs version here is outdated...

### ISSUE THREAD

**Issue by lprc** [w11k/fabs-boilerplate#5]
... and this boilerplate doesn't work with the newest fabs version. Please update!

**Comment by pburgmer** [comment]
You're right: this boilerplate is outdated. I should mark it as deprecated. Please use our Yeoman generator: https://github.com/w11k/fabs-yeoman-generator. I will update the readme with some installation and usage instructions.

**Comment by pburgmer** [comment]
readme updated ...
